//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDBatch {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VDBatch.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions:
        ///
        ///Select AVI files by dropping them onto this window, or by clicking the &quot;Browse&quot; button.
        ///
        ///The job file template to the right will be used when the &quot;Create Job File&quot; button is pressed.  The following strings will be replaced upon processing:
        ///
        ///%p	The full source path
        ///	Example:  E:\videos\source.avi
        ///
        ///%P	The full source path using &quot;\\&quot;
        ///	Example:  E:\\videos\\Source.avi
        ///
        ///%d	The full source directory
        ///	Example:  E:\videos
        ///
        ///%D	The full source directory, using &quot;\\&quot;
        ///	Example:  E:\\videos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // $job &quot;Job %n&quot;
        ///// $input &quot;%p&quot;
        ///// $output &quot;%b-New.%e&quot;
        ///// $state 0
        ///// $id 0000000000000000
        ///// $start_time 0 0
        ///// $end_time 0 0
        ///// $script
        ///
        ///VirtualDub.Open(&quot;%P&quot;,0,0);.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VirtualDub.subset.Delete();
        ///VirtualDub.video.SetRange();
        ///VirtualDub.project.ClearTextInfo();
        ///  // -- $reloadstop --
        ///VirtualDub.SaveAVI(&quot;%B-New.%e&quot;);
        ///VirtualDub.audio.SetSource(1);
        ///VirtualDub.Close();
        ///
        ///// $endjob
        /////
        /////--------------------------------------------------.
        /// </summary>
        internal static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VirtualDub.audio.SetSource(1);
        ///VirtualDub.audio.SetMode(0);
        ///VirtualDub.audio.SetInterleave(1,500,1,0,0);
        ///VirtualDub.audio.SetClipMode(1,1);
        ///VirtualDub.audio.SetConversion(0,0,0,0,0);
        ///VirtualDub.audio.SetVolume();
        ///VirtualDub.audio.SetCompression();
        ///VirtualDub.video.SetDepth(24,24);
        ///VirtualDub.video.SetMode(1);
        ///VirtualDub.video.SetFrameRate(0,1);
        ///VirtualDub.video.SetIVTC(0,0,-1,0);
        ///VirtualDub.video.SetRange(0,0);
        ///VirtualDub.video.SetCompression();
        ///VirtualDub.video.filters.Clear();.
        /// </summary>
        internal static string TemplateBase {
            get {
                return ResourceManager.GetString("TemplateBase", resourceCulture);
            }
        }
    }
}
